"""
issuer_processor_category_dict.py
~~~
The mappings between full card name and issuer/processor/category. Not all credit cards are on here. Some require
manually inputting the issuer, processor, and category.
"""

ipc = {'cards': {'issuer': 'Issuer', 'category': 'Categories', 'processor': 'Processor'},
 'discover it secured card': {'issuer': 'Discover', 'category': 'secured, service', 'processor': 'Discover'},
 'blue cash everyday card from american express': {'issuer': 'American Express',
                                                   'category': 'balance_transfer, cash_back, dining, favorite, starter',
                                                   'processor': 'American Express'},
 'discover it - cashback match': {'issuer': 'Discover', 'category': 'cash_back, dining, favorite, service, starter',
                                  'processor': 'Discover'},
 'starwood preferred guest credit card from american express': {'issuer': 'American Express',
                                                                'category': 'favorite, hotel, travel',
                                                                'processor': 'American Express'},
 'blue cash preferred card from american express': {'issuer': 'American Express',
                                                    'category': 'cash_back, dining, starter',
                                                    'processor': 'American Express'},
 'discover it for students': {'issuer': 'Discover', 'category': 'student', 'processor': 'Discover'},
 'starwood preferred guest business credit card from american express': {'issuer': 'American Express',
                                                                         'category': 'business',
                                                                         'processor': 'American Express'},
 'discover it miles': {'issuer': 'Discover', 'category': 'faux_miles, travel', 'processor': 'Discover'},
 'gold delta skymiles credit card from american express': {'issuer': 'American Express', 'category': 'miles, travel',
                                                           'processor': 'American Express'},
 'amex everyday credit card from american express': {'issuer': 'American Express',
                                                     'category': 'cash_back, favorite, starter',
                                                     'processor': 'American Express'},
 'delta reserve credit card from american express': {'issuer': 'American Express', 'category': 'miles',
                                                     'processor': 'American Express'},
 'chase freedom unlimited': {'issuer': 'Chase', 'category': 'cash_back, military, rewards, starter',
                             'processor': 'Visa'},
 'platinum card from american express for mercedes-benz': {'issuer': 'American Express', 'category': 'affinity',
                                                           'processor': 'American Express'},
 'amazon signature visa card': {'issuer': 'Amazon', 'category': 'online_shopping, service', 'processor': 'Visa'},
 'chase sapphire preferred card': {'issuer': 'Chase', 'category': 'faux_miles, miles, online_shopping, rewards, travel',
                                   'processor': 'Visa'},
 'nhl discover it': {'issuer': 'Discover', 'category': 'affinity', 'processor': 'Discover'},
 'blue for business credit card from american express': {'issuer': 'American Express', 'category': 'business',
                                                         'processor': 'American Express'},
 'jetblue card': {'issuer': 'American Express', 'category': 'miles', 'processor': 'American Express'},
 'usaa cashback rewards plus american express': {'issuer': 'USAA', 'category': 'cash_back, military',
                                                 'processor': 'American Express'},
 'gold delta skymiles business credit card from american express': {'issuer': 'American Express',
                                                                    'category': 'miles, travel',
                                                                    'processor': 'American Express'},
 'ihg rewards club select credit card': {'issuer': 'Chase', 'category': 'hotel', 'processor': 'Mastercard'},
 'platinum card from american express for ameriprise financial': {'issuer': 'American Express', 'category': 'affinity',
                                                                  'processor': 'American Express'},
 'premier rewards gold card from american express': {'issuer': 'American Express', 'category': 'faux_miles, travel',
                                                     'processor': 'American Express'},
 'chase sapphire reserve credit card': {'issuer': 'Chase', 'category': 'cash_back, favorite, military, rewards',
                                        'processor': 'Visa'},
 'discover it chrome for students': {'issuer': 'Discover', 'category': 'student', 'processor': 'Discover'},
 'hilton honors surpass card from american express': {'issuer': 'American Express', 'category': 'hotel',
                                                      'processor': 'American Express'},
 'platinum delta skymiles business credit card from american express': {'issuer': 'American Express',
                                                                        'category': 'miles',
                                                                        'processor': 'American Express'},
 'plum card from american express': {'issuer': 'American Express', 'category': 'business, favorite',
                                     'processor': 'American Express'},
 'simplycash plus business credit card from american express': {'issuer': 'American Express',
                                                                'category': 'business, cash_back, starter',
                                                                'processor': 'American Express'},
 'usaa preferred cash rewards visa signature': {'issuer': 'USAA',
                                                'category': 'cash_back, favorite, low_interest, military, starter',
                                                'processor': 'Visa'},
 'bankamericard credit card': {'issuer': 'Bank of America', 'category': 'balance_transfer, low_interest',
                               'processor': 'Visa'},
 'chase freedom': {'issuer': 'Chase', 'category': 'cash_back, low_interest, online_shopping, starter',
                   'processor': 'Visa'},
 'citi simplicity card - no late fees ever': {'issuer': 'Citi', 'category': 'balance_transfer, low_interest',
                                              'processor': 'Mastercard'},
 'business gold rewards card from american express': {'issuer': 'American Express',
                                                      'category': 'business, favorite, rewards',
                                                      'processor': 'American Express'},
 'capital one quicksilverone cash rewards credit card': {'issuer': 'Capital One',
                                                         'category': 'cash_back, dining, favorite, service, starter',
                                                         'processor': 'Mastercard'},
 'hilton honors card from american express': {'issuer': 'American Express', 'category': 'hotel',
                                              'processor': 'American Express'},
 'hyatt credit card': {'issuer': 'Chase', 'category': 'hotel', 'processor': 'Visa'},
 'usaa secured card visa platinum': {'issuer': 'USAA', 'category': 'favorite, military, secured', 'processor': 'Visa'},
 'virgin atlantic black credit card': {'issuer': 'Bank of America', 'category': 'miles, travel',
                                       'processor': 'Mastercard'},
 'ink business cash credit card': {'issuer': 'Chase', 'category': 'business', 'processor': 'Visa'},
 'schwab investor card from american express': {'issuer': 'American Express', 'category': 'balance_transfer, cash_back',
                                                'processor': 'American Express'},
 'capital one quicksilver cash rewards credit card': {'issuer': 'Capital One',
                                                      'category': 'cash_back, rewards, starter', 'processor': 'Visa'},
 'chase ritz-carlton rewards credit card': {'issuer': 'Chase', 'category': 'hotel, travel', 'processor': 'Visa'},
 'chase slate': {'issuer': 'Chase', 'category': 'balance_transfer, rewards', 'processor': 'Visa'},
 'club carlson radisson rewards visa signature card': {'issuer': 'US Bank', 'category': 'hotel, travel',
                                                       'processor': 'Visa'},
 'united mileageplus explorer card': {'issuer': 'Chase', 'category': 'miles, travel', 'processor': 'Visa'},
 'aboc platinum rewards card': {'issuer': 'ABOC', 'category': 'low_interest, rewards', 'processor': 'Mastercard'},
 'bankamericard travel rewards credit card': {'issuer': 'Bank of America', 'category': 'faux_miles, travel',
                                              'processor': 'Visa'},
 'capital one venture rewards credit card': {'issuer': 'Capital One', 'category': 'rewards, travel',
                                             'processor': 'Visa'},
 'ink business preferred credit card': {'issuer': 'Chase', 'category': 'business', 'processor': 'Visa'},
 'journey student rewards from capital one': {'issuer': 'Capital One', 'category': 'rewards, student',
                                              'processor': 'Visa'},
 'wells fargo cash wise visa card': {'issuer': 'Wells Fargo', 'category': 'cash_back, starter', 'processor': 'Visa'},
 'wells fargo platinum visa card': {'issuer': 'Wells Fargo', 'category': 'balance_transfer, low_interest',
                                    'processor': 'Visa'},
 'american express gold card for ameriprise financial': {'issuer': 'American Express', 'category': 'rewards',
                                                         'processor': 'American Express'},
 'bankamericard cash rewards credit card': {'issuer': 'Bank of America', 'category': 'cash_back, rewards, starter',
                                            'processor': 'Visa'},
 'business green rewards card from american express': {'issuer': 'American Express', 'category': 'business, rewards',
                                                       'processor': 'American Express'},
 'capital one secured mastercard': {'issuer': 'Capital One', 'category': 'secured', 'processor': 'Mastercard'},
 'capital one ventureone rewards credit card': {'issuer': 'Capital One', 'category': 'faux_miles, travel',
                                                'processor': 'Visa'},
 'southwest rapid rewards premier card': {'issuer': 'Chase', 'category': 'miles, travel', 'processor': 'Visa'},
 'u.s. bank cash+ visa signature card': {'issuer': 'US Bank', 'category': 'cash_back, rewards', 'processor': 'Visa'},
 'bank of america business advantage travel rewards world mastercard credit card': {'issuer': 'Bank of America',
                                                                                    'category': 'rewards, travel',
                                                                                    'processor': 'Mastercard'},
 'capital one platinum credit card': {'issuer': 'Capital One', 'category': 'online_shopping, rewards',
                                      'processor': 'Mastercard'},
 'capital one premier dining rewards credit card': {'issuer': 'Capital One', 'category': 'cash_back, dining',
                                                    'processor': 'Mastercard'},
 'capital one spark classic for business': {'issuer': 'Capital One', 'category': 'business', 'processor': 'Visa'},
 'marriott rewards premier credit card': {'issuer': 'Chase', 'category': 'hotel, rewards', 'processor': 'Visa'},
 'navy federal nrewards secured credit card': {'issuer': 'Navy Federal Credit Union', 'category': 'military, secured',
                                               'processor': 'Mastercard'},
 'susan g. komen credit card': {'issuer': 'Bank of America', 'category': 'affinity, cash_back', 'processor': 'Visa'},
 'us bank aeromexico visa signature card': {'issuer': 'US Bank', 'category': 'miles, travel', 'processor': 'Visa'},
 'alaska airlines visa signature credit card': {'issuer': 'Bank of America', 'category': 'miles, travel',
                                                'processor': 'Visa'},
 'bank of america business advantage cash rewards mastercard credit card': {'issuer': 'Bank of America',
                                                                            'category': 'business, cash_back, rewards, starter',
                                                                            'processor': 'Mastercard'},
 'british airways visa signature card': {'issuer': 'Chase', 'category': 'miles, travel', 'processor': 'Visa'},
 'citizens bank cash back plus world mastercard': {'issuer': 'Citizens Bank', 'category': 'cash_back, rewards',
                                                   'processor': 'Mastercard'},
 'u.s. bank cash 365 american express card': {'issuer': 'US Bank', 'category': 'cash_back, online_shopping',
                                              'processor': 'American Express'},
 'us bank lanpass visa signature card': {'issuer': 'US Bank', 'category': 'miles, travel', 'processor': 'Visa'},
 'barclays aadvantage aviator red world mastercard': {'issuer': 'Barclaycard', 'category': 'miles, travel',
                                                'processor': 'Mastercard'},
 'capital one spark card for business': {'issuer': 'Capital One', 'category': 'business', 'processor': 'Visa'},
 'selfscore achieve mastercard for international students': {'issuer': 'SelfScore', 'category': 'student',
                                                             'processor': 'Mastercard'},
 'us bank flexperks select+ american express card': {'issuer': 'US Bank', 'category': 'faux_miles, travel',
                                                     'processor': 'American Express'},
 'virgin atlantic white credit card': {'issuer': 'Bank of America', 'category': 'miles, travel',
                                       'processor': 'Mastercard'},
 'capital one spark cash select for business': {'issuer': 'Capital One', 'category': 'business', 'processor': 'Visa'},
 'bank of america asiana visa signature card': {'issuer': 'Bank of America', 'category': 'miles, travel',
                                                'processor': 'Visa'},
 'bank of the west platinum rewards mastercard credit card': {'issuer': 'Bank of the West', 'category': 'rewards',
                                                              'processor': 'Mastercard'},
 'barclay choice privileges visa signature card': {'issuer': 'Barclaycard', 'category': 'hotel, travel',
                                                   'processor': 'Visa'},
 'barclay wyndham rewards visa card': {'issuer': 'Barclaycard', 'category': 'hotel, travel', 'processor': 'Visa'},
 'business platinum card from american express': {'issuer': 'American Express', 'category': 'business',
                                                  'processor': 'American Express'},
 'capital one spark miles for business': {'issuer': 'Capital One', 'category': 'business, travel', 'processor': 'Visa'},
 'skypass visa secured': {'issuer': 'US Bank', 'category': 'faux_miles, travel', 'processor': 'Visa'},
 'somerset trust company mastercard with scorecard rewards': {'issuer': 'Somerset Trust',
                                                              'category': 'ethical, rewards',
                                                              'processor': 'Mastercard'},
 'aboc standard secured': {'issuer': 'ABOC', 'category': 'secured', 'processor': 'Mastercard'},
 'banco popular avianca vida': {'issuer': 'Banco Popular', 'category': 'miles, travel', 'processor': 'Visa'},
 'barclaycard arrival plus world elite mastercard': {'issuer': 'Barclaycard', 'category': 'miles, travel',
                                                     'processor': 'Mastercard'},
 'barclays hawaiian airlines world elite mastercard': {'issuer': 'Barclaycard', 'category': 'miles, travel',
                                                       'processor': 'Mastercard'},
 'citi thankyou preferred card for college students': {'issuer': 'Citi', 'category': 'rewards, student',
                                                       'processor': 'Mastercard'},
 'clearpoints': {'issuer': 'BBVA Compass', 'category': 'balance_transfer, rewards', 'processor': 'Visa'},
 'fidelity rewards visa signature card': {'issuer': 'US Bank',
                                          'category': 'cash_back, dining, favorite, online_shopping',
                                          'processor': 'Visa'},
 'pnc points visa': {'issuer': 'PNC Bank', 'category': 'balance_transfer, rewards', 'processor': 'Visa'},
 'platinum card from american express': {'issuer': 'American Express', 'category': 'rewards, travel',
                                         'processor': 'American Express'},
 'albina community bank loop visa credit card': {'issuer': 'Albina Community Bank', 'category': 'affinity, ethical',
                                                 'processor': 'Visa'},
 'berkshire bank primor secured visa gold': {'issuer': 'Berkshire Bank', 'category': 'secured', 'processor': 'Visa'},
 'citi diamond preferred card': {'issuer': 'Citi', 'category': 'balance_transfer, rewards', 'processor': 'Mastercard'},
 'citi double cash card': {'issuer': 'Citi', 'category': 'cash_back, rewards, starter', 'processor': 'Mastercard'},
 'navy federal visa signature flagship rewards credit card': {'issuer': 'Navy Federal Credit Union',
                                                              'category': 'military', 'processor': 'Visa'},
 'sdfcu savings secured visa platinum card': {'issuer': 'SDFCU Savings', 'category': 'secured', 'processor': 'Visa'},
 'valero dsrm national bank credit card': {'issuer': 'DSRM National Bank', 'category': 'travel',
                                           'processor': 'Mastercard'},
 'american express platinum card for schwab': {'issuer': 'American Express', 'category': 'rewards',
                                               'processor': 'American Express'},
 'banco popular avianca vuela': {'issuer': 'Banco Popular', 'category': 'miles, travel', 'processor': 'Visa'},
 'barclays lufthansa miles & more world elite mastercard': {'issuer': 'Barclaycard', 'category': 'miles, travel',
                                                            'processor': 'Mastercard'},
 'beneficial state visa platinum credit card': {'issuer': 'Beneficial State Bank', 'category': 'affinity, ethical',
                                                'processor': 'Visa'},
 'citibusiness / aadvantage platinum select world mastercard': {'issuer': 'Citi', 'category': 'miles, travel',
                                                                'processor': 'Mastercard'},
 'berkshire bank primor secured visa classic': {'issuer': 'Berkshire Bank', 'category': 'secured', 'processor': 'Visa'},
 'chase united mileageplus club card': {'issuer': 'Chase', 'category': 'miles, travel', 'processor': 'Visa'},
 'commerce bank visa business platinum': {'issuer': 'Commerce Bank', 'category': 'business', 'processor': 'Visa'},
 'exxon mobil credit card': {'issuer': 'Citi', 'category': 'gas, travel', 'processor': 'Mastercard'},
 'marine federal credit union visa platinum scorecard': {'issuer': 'Marine Federal Credit Union',
                                                         'category': 'military, rewards', 'processor': 'Visa'},
 'national bank of commerce business edition card with business category rewards': {
     'issuer': 'National Bank of Commerce', 'category': 'business, rewards', 'processor': 'Visa'},
 'national bank of commerce business edition card with reward simplicity': {'issuer': 'National Bank of Commerce',
                                                                            'category': 'business',
                                                                            'processor': 'Visa'},
 'air force fcu visa platinum card': {'issuer': 'Air Force FCU', 'category': 'rewards', 'processor': 'Visa'},
 'citi aadvantage executive world elite mastercard': {'issuer': 'Citi', 'category': 'miles, travel',
                                                      'processor': 'Mastercard'},
 'golden1 credit union platinum rewards for students': {'issuer': 'Golden1', 'category': 'student',
                                                        'processor': 'Visa'},
 'shell drive for five credit card': {'issuer': 'Citi', 'category': 'gas, travel', 'processor': 'Mastercard'},
 'alliant visa platinum card': {'issuer': 'Alliant', 'category': 'cash_back', 'processor': 'Visa'},
 'citi secured mastercard': {'issuer': 'Citi', 'category': 'secured', 'processor': 'Mastercard'},
 'walmart mastercard': {'issuer': 'Walmart', 'category': 'cash_back', 'processor': 'Mastercard'},
 'commerce bank kansas city royals with rewards': {'issuer': 'Commerce Bank', 'category': 'affinity, cash_back',
                                                   'processor': 'Mastercard'},
 'sustain green mastercard': {'issuer': 'Commerce Bank', 'category': 'affinity, ethical', 'processor': 'Mastercard'},
 'ameriprise world mastercard': {'issuer': 'Barclaycard', 'category': 'rewards', 'processor': 'Mastercard'},
 'comerica visa signature bonus rewards': {'issuer': 'Comerica', 'category': 'cash_back, rewards', 'processor': 'Visa'},
 'citi prestige': {'issuer': 'Citi', 'category': 'travel', 'processor': 'Mastercard'},
 'td bank aeroplan visa signature card': {'issuer': 'TD Bank', 'category': 'miles, travel', 'processor': 'Visa'},
 'barclays frontier airlines world mastercard': {'issuer': 'Barclaycard', 'category': 'miles, travel',
                                                 'processor': 'Mastercard'},
 'comerica cash rewards american express card': {'issuer': 'Comerica', 'category': 'cash_back',
                                                 'processor': 'American Express'},
 'chevron and texaco advantage visa card': {'issuer': 'Synchrony Bank', 'category': 'gas, travel', 'processor': 'Visa'},
 'bp visa credit card': {'issuer': 'Synchrony Bank', 'category': 'gas, travel', 'processor': 'Visa'},
 'walmart credit card': {'issuer': 'Synchrony Bank', 'category': 'cash_back', 'processor': 'Mastercard'},
 'wells fargo propel american express card': {'issuer': 'Wells Fargo', 'category': 'rewards',
                                              'processor': 'American Express'},
 'citgo rewards card': {'issuer': 'Synchrony Bank', 'category': 'travel', 'processor': 'Mastercard'},
 'mbna best western rewards mastercard': {'issuer': 'MBNA', 'category': 'hotel, travel', 'processor': 'Mastercard'}}
