"""
short_name_dict.py
~~~
All of the mappings between full card names and short card names. Not all credit cards are on here. Some credit cards
require manually inputting the short card name.
"""

short_name_dict = {'name': 'short_name', 'aboc platinum rewards card': 'ABOC Platinum Card', 'aboc standard secured': 'ABOC Secured',
 'air force fcu visa platinum card': 'Air Force FCU Card',
 'alaska airlines visa signature credit card': 'Alaska Airlines Visa',
 'albina community bank loop visa credit card': 'Albina Card', 'alliant visa platinum card': 'Alliant Card',
 'amazon signature visa card': 'Amazon Visa',
 'american express gold card for ameriprise financial': 'Amex Ameriprise Gold Card',
 'american express platinum card for schwab': 'Schwab Card', 'ameriprise world mastercard': 'Ameriprise Card',
 'amex everyday credit card from american express': 'Amex EveryDay', 'banco popular avianca vida': 'Banco Popular Card',
 'banco popular avianca vuela': 'Banco Popular Card',
 'bank of america asiana visa signature card': 'Bank of America Asiana Card',
 'bank of america business advantage cash rewards mastercard credit card': 'BofA Advantage Cash',
 'bank of america business advantage travel rewards world mastercard credit card': 'BofA Advantage Travel',
 'bank of the west platinum rewards mastercard credit card': 'Bank of the West Plat Card',
 'bankamericard cash rewards credit card': 'BankAmericard Cash', 'bankamericard credit card': 'BankAmericard',
 'bankamericard travel rewards credit card': 'BankAmericard Travel ',
 'barclay choice privileges visa signature card': 'Barclay Choice Card',
 'barclay wyndham rewards visa card': 'Barclay Wyndham Card',
 'barclaycard arrival plus world elite mastercard': 'Barclay World Elite Card',
 'barclays aadvantage aviator red world mastercard': 'Barclays AAdvantage Card',
 'barclays frontier airlines world mastercard': 'Barclays Frontier Card',
 'barclays hawaiian airlines world elite mastercard': 'Barclays Hawaiian Air Card',
 'barclays lufthansa miles & more world elite mastercard': 'Barclays Lufthansa Card',
 'beneficial state visa platinum credit card': 'Beneficial State VISA',
 'berkshire bank primor secured visa classic': 'Berkshire Bank Classic',
 'berkshire bank primor secured visa gold': 'Berkshire Bank Gold',
 'blue cash everyday card from american express': 'Blue Cash Everyday Card',
 'blue cash preferred card from american express': 'Blue Cash Preferred Card ',
 'blue for business credit card from american express': 'Blue for Business', 'bp visa credit card': 'BP Visa Card',
 'british airways visa signature card': 'British Airways Visa',
 'business gold rewards card from american express': 'Business Gold Rewards ',
 'business green rewards card from american express': 'Business Green Rewards',
 'business platinum card from american express': 'Business Platinum Card ', 'capital one platinum card': 'TRUE',
 'capital one platinum credit card': 'Capital One Platinum ',
 'capital one premier dining rewards credit card': 'Capital One Premier ',
 'capital one quicksilver cash rewards credit card': 'Capital One Quicksilver ',
 'capital one quicksilverone cash rewards credit card': 'CapitalOne QuicksilverOne',
 'capital one secured mastercard': 'Capital One Secured', 'capital one spark card for business': 'Capital One Spark ',
 'capital one spark cash select for business': 'Capital One Spark Cash',
 'capital one spark classic for business': 'Capital One Spark Classic ',
 'capital one spark miles for business': 'Capital One Spark Miles ',
 'capital one venture rewards credit card': 'Capital One Venture',
 'capital one ventureone rewards credit card': 'Capital One VentureOne ', 'chase freedom': 'Chase Freedom',
 'chase freedom unlimited': 'Chase Freedom Unlimited', 'chase ritz-carlton rewards credit card': 'Chase Ritz Card',
 'chase sapphire preferred card': 'Chase Sapphire Preferred ',
 'chase sapphire reserve credit card': 'Chase Sapphire Reserve ', 'chase slate': 'Chase Slate',
 'chase united mileageplus club card': 'Chase United Card', 'chevron and texaco advantage visa card': 'Chevron Card',
 'citgo rewards card': 'Citgo Rewards Card', 'citi aadvantage executive world elite mastercard': 'Citi AAdvantage Card',
 'citi diamond preferred card': 'Citi Diamond Preferred ', 'citi double cash card': 'Citi Double Cash ',
 'citi prestige': 'Citi Prestige', 'citi secured mastercard': 'Citi Secured Mastercard',
 'citi simplicity card - no late fees ever': 'Citi Simplicity Card ',
 'citi thankyou preferred card for college students': 'Citi Preferred Student',
 'citibusiness / aadvantage platinum select world mastercard': 'CitiBusiness / AAdvantage',
 'citizens bank cash back plus world mastercard': 'Citizens Bank Cash Back+', 'clearpoints': 'Clearpoints',
 'club carlson radisson rewards visa signature card': 'Club Carlson Radisson',
 'comerica cash rewards american express card': 'Comerica Rewards Amex Card',
 'comerica visa signature bonus rewards': 'Comerica Visa Signature ',
 'commerce bank kansas city royals with rewards': 'Commerce Bank Kansas City',
 'commerce bank visa business platinum': 'Commerce Bank Card',
 'delta reserve credit card from american express': 'Delta Amex Card',
 'discover it - cashback match': 'Discover it - Cashback ',
 'discover it chrome for students': 'Discover chrome Student', 'discover it for students': 'Discover it for Students',
 'discover it miles': 'Discover it Miles', 'discover it secured card': 'Discover It Secured Card',
 'exxon mobil credit card': 'Exxon Mobil Card', 'fidelity rewards visa signature card': 'Fidelity Rewards Visa',
 'gold delta skymiles business credit card from american express': 'Gold Delta SkyMiles Biz',
 'gold delta skymiles credit card from american express': 'Gold Delta SkyMiles ',
 'golden1 credit union platinum rewards for students': 'Golden1 Student Card',
 'hilton honors card from american express': 'Hilton Amex Card',
 'hilton honors surpass card from american express': 'Hilton Honors Surpass', 'hyatt credit card': 'Hyatt Credit Card',
 'ihg rewards club select credit card': 'IHG Rewards Card', 'ink business cash credit card': 'Ink Business Cash',
 'ink business preferred credit card': 'Ink Business Preferred ', 'jetblue card': 'JetBlue Card',
 'journey student rewards from capital one': 'Journey Student Rewards ',
 'marine federal credit union visa platinum scorecard': 'Marine FDCU Card',
 'marriott rewards premier credit card': 'Marriott Rewards Premier',
 'mbna best western rewards mastercard': 'Best Western Card',
 'national bank of commerce business edition card with business category rewards': 'National Bank Business',
 'national bank of commerce business edition card with reward simplicity': 'National Bank Simple',
 'navy federal nrewards secured credit card': 'NavyFederal Secured',
 'navy federal visa signature flagship rewards credit card': 'NavyFed Signature',
 'nhl discover it': 'NHL Discover it Card', 'platinum card from american express': 'Platinum Amex',
 'platinum card from american express for ameriprise financial': 'Amex Ameriprise Card',
 'platinum card from american express for mercedes-benz': 'Amex Mercedes Card',
 'platinum delta skymiles business credit card from american express': 'Platinum Delta Amex',
 'plum card from american express': 'Plum Card Amex', 'pnc points visa': 'PNC points',
 'premier rewards gold card from american express': 'Amex Premier Rewards',
 'schwab investor card from american express': 'Schwab Investor',
 'sdfcu savings secured visa platinum card': 'SDFCU Secured',
 'selfscore achieve mastercard for international students': 'SelfScore Card',
 'shell drive for five credit card': 'Shell Card',
 'simplycash plus business credit card from american express': 'SimplyCash Plus ',
 'skypass visa secured': 'Skypass Secured',
 'somerset trust company mastercard with scorecard rewards': 'Somerset Trust Card',
 'southwest rapid rewards premier card': 'Southwest Card',
 'starwood preferred guest business credit card from american express': 'Starwood Preferred Biz',
 'starwood preferred guest credit card from american express': 'Starwood Preferred',
 'susan g. komen credit card': 'Susan G. Komen', 'sustain green mastercard': 'Sustain Green',
 'td bank aeroplan visa signature card': 'TD Bank Card', 'u.s. bank cash 365 american express card': 'US Bank Cash 365',
 'u.s. bank cash+ visa signature card': 'US Bank Cash+', 'united mileageplus explorer card': 'United Explorer',
 'us bank aeromexico visa signature card': 'US Bank Aeromexico Card',
 'us bank flexperks select+ american express card': 'US Bank FlexPerks',
 'us bank lanpass visa signature card': 'LANPASS Card',
 'usaa cashback rewards plus american express': 'USAA Cashback Amex',
 'usaa preferred cash rewards visa signature': 'USAA Cash', 'usaa secured card visa platinum': 'USAA Secured',
 'valero dsrm national bank credit card': 'Valero Card', 'virgin atlantic black credit card': 'Virgin Atlantic Black',
 'virgin atlantic white credit card': 'Virgin Atlantic Card', 'walmart credit card': 'Walmart Credit Card',
 'walmart mastercard': 'Walmart Mastercard', 'wells fargo cash wise visa card': 'Wells Fargo Cash Wise',
 'wells fargo platinum visa card': 'Wells Fargo Card', 'wells fargo propel american express card': 'Wells Fargo Propel'}
